apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ybui2svcw-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ff8699e2be.vvc7.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:2df4fe72b543050f5a91bc2044b9b09478ef26d6@sha256:24efa9bcdd196b47b9d2b1d16108bccd02e10165337341e8d266ffa37a22010e
          name: container-image
